FROM tensorflow/tensorflow:2.4.0-gpu
RUN apt-get update -y && apt-get upgrade -y && apt install -y libgl1-mesa-glx && apt install redis-server

# start redis server
RUN redis-server

# install node and npm
# RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
# RUN . ~/.nvm/nvm.sh 
# RUN nvm install 10.15.2
# RUN apt install -y npm
